package ml.sgworlds.dimension;

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import ml.sgworlds.api.world.IWorldData;
import ml.sgworlds.api.world.WorldFeatureProvider;
import ml.sgworlds.api.world.WorldFeatureProvider.IWorldFeature;
import ml.sgworlds.api.world.WorldFeatureType;
import net.minecraft.nbt.NBTTagCompound;
import net.minecraft.nbt.NBTTagList;
import net.minecraft.world.World;
import net.minecraft.world.WorldProvider;
import net.minecraft.world.WorldSavedData;
import net.minecraftforge.common.DimensionManager;
import stargatetech2.api.StargateTechAPI;
import stargatetech2.api.stargate.Address;

import com.google.common.collect.HashMultimap;
import com.google.common.collect.Multimap;

import cpw.mods.fml.common.FMLLog;

/**
 * Stores info for individual worlds generated by SGWorlds. e.g. Day Length, # of suns/moons, etc.
 * Pre-generated when a world is started.
 * @author Matchlighter
 */
public class SGWorldData extends WorldSavedData implements IWorldData {

	private String name = null;
	private String designation;
	private Address primaryAddress;
	private int dimensionId = 0;
	private long seed;
	private Multimap<WorldFeatureType, IWorldFeature> features;
	private SGWorldProvider worldProvider;
	
	public SGWorldData(String designation, Address address, Multimap<WorldFeatureType, IWorldFeature> features) {
		super(getUID(designation));
		this.designation = designation;
		this.primaryAddress = address;
		this.features = features;
		
		for (IWorldFeature feat : new HashSet<IWorldFeature>(this.features.values())) {
			feat.setWorldData(this);
		}
	}
	
	/** Constructor used when Loading from NBT */
	public SGWorldData(String uid) {
		super(uid);
		features = HashMultimap.create();
	}

	public String getDisplayName() {
		return (name == null || name.equals("")) ? designation : name;
	}
	
	@Override
	public void readFromNBT(NBTTagCompound nbt) {
		this.designation = nbt.getString("designation");
		this.name = nbt.getString("name");
		this.primaryAddress = StargateTechAPI.api().getStargateNetwork().parseAddress(nbt.getString("address"));
		this.dimensionId = nbt.getInteger("dim");
		
		NBTTagList list = nbt.getTagList("features");
		for (int i=0; i<list.tagCount(); i++) {
			NBTTagCompound ftag = (NBTTagCompound)list.tagAt(i);
			String id = ftag.getString("identifier");
			
			WorldFeatureProvider prov = FeatureManager.instance.getFeatureProvider(id);
			if (prov != null) {
				IWorldFeature feature = prov.loadFeatureFromNBT(ftag.getCompoundTag("data"));
				features.put(prov.type, feature);
				
				List<WorldFeatureType> secondaryTypes = new ArrayList<WorldFeatureType>();
				feature.getSecondaryTypes(secondaryTypes);
				for (WorldFeatureType stype : secondaryTypes) {
					if (stype == prov.type) continue;
					features.put(stype, feature);
				}
			} else {
				//if (Registry.config.ignoreMissingFeature)
				FMLLog.severe("Could not find the Feature Provider for \"%s\"", id);
				//else
				//	throw new RuntimeException(String.format("Could not find the Feature Provider for \"%s\".", id));
			}
		}
		
		SGWorldManager.instance.registerSGWorld(this);
	}

	@Override
	public void writeToNBT(NBTTagCompound nbt) {
		nbt.setString("designation", designation);
		nbt.setString("name", name);
		nbt.setString("address", primaryAddress.toString());
		nbt.setInteger("dim", dimensionId);
		
		NBTTagList list = new NBTTagList();
		Set<IWorldFeature> featureSet = new HashSet<WorldFeatureProvider.IWorldFeature>(features.values());
		for (IWorldFeature ft : featureSet) {
			NBTTagCompound ftag = new NBTTagCompound();
			ftag.setString("identifier", ft.getProvider().identifier);
			
			NBTTagCompound dataTag = new NBTTagCompound();
			ft.writeNBTData(dataTag);
			ftag.setCompoundTag("data", dataTag);
			
			list.appendTag(ftag);
		}
		nbt.setTag("features", list);
	}
	
	public int getDimensionId() {
		return dimensionId;
	}
	
	public void setDimensionId(int dimensionId) {
		if (this.dimensionId == 0) this.dimensionId = dimensionId;
	}
	
	public Address getPrimaryAddress() {
		return primaryAddress;
	}
	
	public String getDesignation() {
		return designation;
	}
	
	public long getWorldSeed() {
		return seed;
	}
	
	@Override
	public WorldProvider getWorldProvider() {
		return worldProvider;
	}
	
	public void setWorldProvider(SGWorldProvider pvdr) {
		this.worldProvider = pvdr;
	}
	
	/**
	 * Returns the first found feature of the specified type. Mainly for use when there is only one of that type.
	 */
	public IWorldFeature getFeature(WorldFeatureType type) {
		List<IWorldFeature> tfeats = getFeatures(type);
		return tfeats.size() > 0 ? tfeats.get(0) : null;
	}
	
	/**
	 * Should never return null
	 */
	public List<IWorldFeature> getFeatures(WorldFeatureType type) {
		if (type == WorldFeatureType.ALL) return new ArrayList<WorldFeatureProvider.IWorldFeature>(features.values());
		return new ArrayList<WorldFeatureProvider.IWorldFeature>(features.get(type));
	}

	public String getUID() {
		return getUID(designation);
	}
	
	public static String getUID(String designation) {
		return "sgworlddata_" + designation;
	}
	
	public static SGWorldData loadData(String designation) {
		World overWorld = DimensionManager.getWorld(0);
		String ufn = getUID(designation);
		SGWorldData data = (SGWorldData)overWorld.loadItemData(SGWorldData.class, ufn);
		
		if (data == null) { //Somebody did something stupid.
			FMLLog.severe("Could not load world data for SGWorlds world %s", designation);
			data = new WorldDataGenerator().generateRandomWorld();
			overWorld.setItemData(ufn, data);
			data.markDirty();
		}
		return data;
	}
}
